SerafimWeb/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SerafimeWeb.Models;
using SerafimeWeb.ViewModels;

namespace SerafimeWeb.Controllers
{
    public class LoginController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;

        public LoginController(UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Login(string returnUrl = null)
        {
            return View(new LoginViewModel { ReturnUrl = returnUrl });
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result =
                    await _signInManager.PasswordSignInAsync(model.UserName, model.Password, model.RememberMe, false);
                if (result.Succeeded)
                {
                    if (!string.IsNullOrEmpty(model.ReturnUrl) && Url.IsLocalUrl(model.ReturnUrl))
                    {
                        return Redirect(model.ReturnUrl);
                    }
                    else
                    {
                        User user = new User { UserName = model.UserName };
                        //// установка куки
                        //await _signInManager.SignOutAsync();
                        //await _signInManager.SignInAsync(user, false);

                        return RedirectToAction("Index", "Home");
                    }

                }
                ModelState.AddModelError("", "Непрвальный логин (и)или пароль");
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LogOff()
        {
            // удаляем аутентификационные куки
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

SerafimWeb/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SerafimeWeb.Models;
using SerafimeWeb.ViewModels;

namespace SerafimeWeb.Controllers
{
    public class RegisterController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;

        public RegisterController(UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }
        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Register(RegisterViewModel model, string roleString)
        {
            if (ModelState.IsValid)
            {
                User user = new User
                {
                    UserName = model.UserName,
                    FullName = model.FullName,
                    Email = model.Email,
                    Birthdate = model.Birthdate,
                    Address = model.Address,
                    PhoneNumber = model.PhoneNumber,
                    PhoneNumberConfirmed = true,
                    EmailConfirmed = true
                };

                // добавляем пользователя
                var result = await _userManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    if (!string.IsNullOrEmpty(roleString))
                    {
                        if(roleString == "0")
                        {
                            await _userManager.AddToRoleAsync(user, "admin");
                        }
                        else
                        {
                            await _userManager.AddToRoleAsync(user, "user");
                            
                        }
                        await _userManager.AddClaimAsync(user, new Claim(ClaimTypes.Email, user.Email));
                    }

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }
    }
}

SerafimWeb/Controllers/UsersController.cs
using System.Linq;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SerafimeWeb.Models;
using SerafimeWeb.ViewModels;

namespace SerafimeWeb.Controllers
{
    public class UsersController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<User> _userManager;
        private const int PageSize = 4;

        public UsersController(UserManager<User> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public IActionResult List(SearchType searchType, string searchString, int page = 1)
        {
            IQueryable<User> users = _userManager.Users.OrderBy(p => p.Email);

            if (!string.IsNullOrEmpty(searchString))
            {
                switch (searchType)
                {
                    case SearchType.SearchByLogin:
                        users = users.Where(user => user.UserName.Contains(searchString));
                        break;

                    case SearchType.SearchByFullName:
                        users = users.Where(user => user.FullName.Contains(searchString));
                        break;

                    case SearchType.SearchByEmail:
                        users = users.Where(user => user.Email.Contains(searchString));
                        break;

                    default:
                        users = users.Where(user => user.UserName.Contains(searchString));
                        break;
                }
            }

            ListViewModel userListViewModel = new ListViewModel
            {
                Users = users
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize),

                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = users.Count()
                },
                SearchString = searchString,
                SearchType = searchType
            };

            return View(userListViewModel);
        }
    }
}

SerafimWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SerafimWeb</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">SerafimWeb</a>

        @if (User.Identity.IsAuthenticated)
        {
            if (User.IsInRole("admin"))
            {
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown">
                            Управление пользователями
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-controller="Users" asp-action="List">Список пользователей</a>
                            <a class="dropdown-item" asp-controller="Register" asp-action="Register">Зарегистрировать пользователя</a>
                        </div>
                    </li>
                </ul>

                <ul class="navbar-nav ml-auto">
                    <li>
                        <form class="nav-item" method="post" asp-controller="Login" asp-action="LogOff">
                            <button type="submit" class="btn">Выход</button>
                        </form>
                    </li>
                </ul>

            }
            else if (User.IsInRole("user"))
            {
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown">
                            Управление пользователями
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-controller="Users" asp-action="List">Список пользователей</a>
                        </div>
                    </li>
                </ul>

                <ul class="navbar-nav ml-auto">
                    <li>
                        <form class="nav-item" method="post" asp-controller="Login" asp-action="LogOff">
                            <button type="submit" class="btn">Выход</button>
                        </form>
                    </li>
                </ul>
            }
            else
            {
                <ul class="navbar-nav ml-auto">
                    <li>
                        <form class="nav-item" method="post" asp-controller="Login" asp-action="LogOff">
                            <button type="submit" class="btn">Выход</button>
                        </form>
                    </li>
                </ul>
            }
        }
        else
        {
            <ul class="navbar-nav ml-auto">
                <li>
                    <a class="nav-link" asp-controller="Login" asp-action="Login">Вход</a>
                </li>
            </ul>
        }
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - SerafimWeb</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>